baseURL = "https://psugumar2610.github.io/NamahNest-sugumar/"
relativeURLs = true


title = 'Thiruvannamalai Arunachaleswarar Temple – History & Significance'
theme = 'namahNest'

[params]
  description = 'Explore Thiruvannamalai’s sacred Arunachaleswarar Temple – history, legends, Girivalam significance, and visitor guide for spiritual seekers.'

[markup]
  [markup.highlight]
    noClasses = false
    style = "github"
    useClasses = false
    lineNos = false
    codeFences = true  # Ensure code block fences are enabled
  [markup.goldmark]
    [markup.goldmark.parser]
      attribute = true

