baseURL = "https://psugumar2610.github.io/NamahNest-sugumar/"
relativeURLs = true
canonifyURLs = true

title = "NamahNest"
theme = "namahNest"


[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 10

  [[menu.main]]
  name = "Temple"
  url = "/temple"
  weight = 30

  [[menu.main]]
  name = "Ashta Lingam"
  url = "/thiru--asta--lingam"
  weight = 20

  [[menu.main]]
  name = "Thiruvasagam"
  url = "/swamy.songs"
  weight = 40

  [[menu.main]]
  name = "Author"
  url = "/author"
  weight = 50
  params = { target = "_blank" }


[markup]
  [markup.highlight]
    noClasses = false


