baseURL = "https://example.org/"
languageCode = "en-us"
title = "Dynamic Hugo Menu Example"
canonifyURLs = false

[menu]


  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 10

  [[menu.main]]
  name = "Temple"
  url = "/temple"
  weight = 30

  [[menu.main]]
  name = "Ashta Lingam"
  url = "/thiru--asta--lingam"
  weight = 20

  [[menu.main]]
  name = "Thiruvasagam"
  url = "/swamy.songs"
  weight = 40

  [[menu.main]]
  name = "ABOUT THE AUTHOR"
  url = "/swamy.songs"
  weight = 50

[markup]
  [markup.highlight]
    noClasses = false


